#!groovy

node('Slave1Centos'){
    def IMAGE = readMavenPom().getArtifactId()
    def VERSION = readMavenPom().getVersion()
    def server = Artifactory.server 'Art'
    def mvnHome = tool 'MavenPet_3.6.3'  //global variable for maven installations in jenkins
    buildName '${JOB_NAME}_${BUILD_NUMBER}'
    timestamps{//timestamps, Prepend all console output generated by the Pipeline run with the time at which the line was emitted
        stage ('GitHub Preparation') {
            checkout scm
            git 'https://github.com/arhangelwow/spring-petclinic'
        }//stage 1
        stage ('Maven clean + compile') {
            withEnv(["PATH+MAVEN=${mvnHome}/bin"]) {
                sh "mvn clean compile"
            }
        }//stage 2
        stage ('Maven package') {
            withEnv(["PATH+MAVEN=${mvnHome}/bin"]) {
                sh "mvn package"
            }
        }//stage 3
        stage('SonarQube Analysis') {
            withSonarQubeEnv('sonar') {
                withEnv(["PATH+MAVEN=${mvnHome}/bin"]) {
                    sh '''cd ${WORKSPACE}/
                        mvn sonar:sonar'''
                }
            }
        }//stage 4 
        stage ('Artifactory') {
            withEnv(["PATH+MAVEN=${mvnHome}/bin"]) {
                def uploadSpec = 
                """
                {
                "files": [
                    {
                    "pattern": "${env.WORKSPACE}/target/*.jar",
                    "target": "libs-release-local/${IMAGE}_${VERSION}_${BUILD_TIMESTAMP}_${BUILD_NUMBER}.jar",
                    "props": "type=jar;status=ready"
                    }
                ]
                }
                """
                buildInfo=server.upload(uploadSpec) 
                server.publishBuildInfo(buildInfo)  
            }
        }//stage 5
        stage('Start Petclinic Website, Deploy Stage') {
            withEnv(["PATH+MAVEN=${mvnHome}/bin", "JENKINS_NODE_COOKIE=do_not_kill", "BUILD_ID=do_not_kill"]) {
                def downloadSpec = 
                """
                {
                "files": [
                    {
                    "pattern": "libs-release-local/*_${BUILD_NUMBER}.jar",
                    "target": "${WORKSPACE}/builds/",
                    "props": "type=jar;status=ready"
                    }
                ]
                }
                """
                buildInfo=server.download(downloadSpec)    
                sh """cd ${WORKSPACE}/
                mvn clean install
                cd ${WORKSPACE}/builds/
                nohup java -jar ${IMAGE}_${VERSION}_${BUILD_TIMESTAMP}_${BUILD_NUMBER}.jar &"""
            }
        }
    }
}
